#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Turn a file into a C array so the kernel can carry it in its own image.

Used for the initial ramdisk. A bootloader that can pass a module is the normal
path and is still preferred, but QEMU will not hand one to a bare ELF on the
ARM and RISC-V virt machines, and plenty of embedded boot flows cannot pass one
either. Linking the archive into .rodata means every architecture has a /boot
whether or not anything handed it one.

  python tools/bin2c.py dist/x86_64/initrd.tar build/gen/initrd_blob.c
"""

import os
import sys


def main(src, dst):
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)

    data = b""
    if src and os.path.exists(src):
        with open(src, "rb") as fh:
            data = fh.read()

    out = ["/* Generated by tools/bin2c.py from %s - do not edit. */\n"
           % (src or "nothing"),
           "#include <rk/types.h>\n\n"]

    if not data:
        # An empty blob is a valid outcome: the mount is skipped and the
        # kernel behaves exactly as it did before there was one.
        out.append("const unsigned char rk_builtin_initrd[1] = { 0 };\n")
        out.append("const unsigned long rk_builtin_initrd_len = 0;\n")
    else:
        out.append("const unsigned char rk_builtin_initrd[] __attribute__((aligned(8))) = {\n")
        for i in range(0, len(data), 16):
            row = ", ".join("0x%02x" % b for b in data[i:i + 16])
            out.append("\t%s,\n" % row)
        out.append("};\n")
        out.append("const unsigned long rk_builtin_initrd_len = %dul;\n" % len(data))

    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("".join(out))

    print("  BIN2C   %s -> %s (%d bytes)" % (src or "nothing", dst, len(data)))
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: bin2c.py <input> <output.c>")
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
