#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# Rebuild the v2.0.0 branch from main.
#
# The repository is split deliberately. `main` carries everything: the kernel,
# the documentation site and the community files. `v2.0.0` carries the project
# alone - sources, headers, the user program, tests, build and the technical
# documentation under docs/.
#
# Doing that split by hand is how the two drift apart, so it is a script. Run
# it after anything on main that should reach the version branch:
#
#   sh tools/sync-v2-branch.sh          # rebuild and show what changed
#   sh tools/sync-v2-branch.sh --push   # and push it
#
# README.md is deliberately identical on both branches. That is why the links
# in it pointing at community files are absolute - those files are not here.
set -eu

BRANCH=v2.0.0
PUSH=0
[ "${1:-}" = "--push" ] && PUSH=1

# Everything that belongs to main and only to main.
SITE="web media tools/mksite.py tools/checklinks.py tools/mksocial.py tools/mkdocx.py .github/workflows/pages.yml"
COMMUNITY="SECURITY.md GOVERNANCE.md ROADMAP.md CODE_OF_CONDUCT.md CONTRIBUTING.md .github/ISSUE_TEMPLATE .github/pull_request_template.md .github/CODEOWNERS .github/FUNDING.yml"

start=$(git rev-parse --abbrev-ref HEAD)
main=$(git rev-parse --short refs/heads/main)

git checkout -q -B "$BRANCH" refs/heads/main
for path in $SITE $COMMUNITY; do
	[ -e "$path" ] || continue
	git rm -r -q "$path"
done

if git diff --cached --quiet; then
	echo "  nothing to remove; $BRANCH already matches main"
else
	git commit -q -m "The kernel alone, from main at $main

The documentation site and the community files live on main, which is where a
visitor lands and where releases are tagged from. This branch carries the
project and nothing else.

README.md is byte-identical to main's; every link in it that points at a file
living only on main is absolute for exactly that reason.

Regenerated by tools/sync-v2-branch.sh."
fi

echo "  $BRANCH is now $(git rev-parse --short HEAD), from main at $main"
git ls-tree --name-only HEAD | tr '\n' ' '
echo

if [ "$PUSH" = "1" ]; then
	# Fully qualified: a branch and a tag share this name, so an unqualified
	# refspec is ambiguous and git refuses it.
	git push -f origin "refs/heads/$BRANCH:refs/heads/$BRANCH"
	echo "  pushed"
fi

git checkout -q "$start"
